using System;using System.Collections;using System.Collections.Generic;using System.Reflection;using System.Text;using UnityEngine;
namespace AutocatBridge {
// Renderer-only experiment. Never calls CatCosmetics.Equip or any Steam mutator.
public sealed class CosmeticPreview {
 const BindingFlags Flags=BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance|BindingFlags.Static;
 readonly Assembly game;readonly Func<string> prefs;readonly Action<string> log;readonly Action<string,int> broadcast;readonly Dictionary<int,object> catalog=new Dictionary<int,object>();readonly List<Action> restore=new List<Action>();
 readonly Dictionary<string,List<Func<bool>>> expected=new Dictionary<string,List<Func<bool>>>(); object cat,cosmetics;string originalPrefs,originalEquipped;readonly Dictionary<string,int> selectedSlots=new Dictionary<string,int>();int selected=-1;public bool Active{get{return selected>=0||selectedSlots.Count>0;}}public string Catalog{get;private set;}
 static object Field(object obj,string name){return obj.GetType().GetField(name,Flags).GetValue(obj);}
 static object Call(object obj,string name,params object[] args){foreach(var m in obj.GetType().GetMethods(Flags))if(m.Name==name&&m.GetParameters().Length==args.Length)return m.Invoke(obj,args);throw new MissingMethodException(name);}
 object Instance(string type,string field){return game.GetType(type,true,false).GetField(field,Flags).GetValue(null);}
 string Equipped(){var ids=new List<string>();foreach(var item in (IEnumerable)Field(cosmetics,"EquippedItems"))ids.Add(Call(item,"get_Id").ToString());return String.Join(",",ids.ToArray());}
 public CosmeticPreview(Assembly assembly,Func<string> savedPreferences,Action<string> logger,Action<string,int> broadcaster){game=assembly;prefs=savedPreferences;log=logger;broadcast=broadcaster;cat=Instance("BongoCat.Cat","Instance");cosmetics=Instance("BongoCat.CatCosmetics","Instance");if(cat==null||cosmetics==null)throw new Exception("Cat not ready");var reference=Instance("BongoCat.SteamItemIdReference","Inst");var entries=(IDictionary)Field(reference,"RuntimeItems");int owned=0;var rows=new List<string>();foreach(DictionaryEntry pair in entries){var item=pair.Value;if(item==null||!(bool)Call(item,"get_IsCosmetic"))continue;int id=(int)Call(item,"get_Id");if(id<0||catalog.ContainsKey(id))throw new Exception("Invalid/duplicate cosmetic ID");catalog.Add(id,item);bool has=(bool)Call(item,"get_IsOwned");if(has)owned++;rows.Add(id.ToString()+"~"+Field(item,"ItemSlot").ToString()+"~"+(has?"1":"0")+"~"+Convert.ToBase64String(Encoding.UTF8.GetBytes(Call(item,"get_ItemName").ToString())));}if(catalog.Count==0)throw new Exception("Empty cosmetic catalog");Catalog="CATALOG|"+String.Join(";",rows.ToArray());log("discovered="+catalog.Count.ToString()+" owned="+owned.ToString()+" mechanism=renderer-only");}
 void Snapshot(){originalPrefs=prefs();originalEquipped=Equipped();restore.Clear();foreach(var name in new[]{"_catNormal","_catLeft","_catNormalFront","_catRightFront"}){var field=cat.GetType().GetField(name,Flags);var value=field.GetValue(cat);restore.Add(()=>field.SetValue(cat,value));}foreach(var name in new[]{"_hatImage","_catImage","_catFront"}){var img=Field(cat,name);var prop=img.GetType().GetProperty("sprite");var value=prop.GetValue(img,null);var enabled=img.GetType().GetProperty("enabled");var was=enabled.GetValue(img,null);restore.Add(()=>{prop.SetValue(img,value,null);enabled.SetValue(img,was,null);});}var transform=Field(cat,"_hatImage").GetType().GetProperty("transform").GetValue(Field(cat,"_hatImage"),null);var scale=transform.GetType().GetProperty("localScale");var oldScale=scale.GetValue(transform,null);restore.Add(()=>scale.SetValue(transform,oldScale,null));}
 void ValidateAssets(object item){string slot=Field(item,"ItemSlot").ToString();if(slot=="hat"){if(Field(item,"FullImage")==null)throw new Exception("Missing hat asset");}else if(slot=="skin"){var cache=Instance("BongoCat.MemoryImageCache","Instance");string name=Call(item,"get_ItemName").ToString().Replace(" ","");foreach(var suffix in new[]{"Left","LeftPunch","Right","RightPunch"})if(Call(cache,"GetSprite",name+suffix)==null)throw new Exception("Missing skin asset");}else throw new Exception("Unsupported cosmetic slot");}
 public void Clear(string slot){float start=Time.realtimeSinceStartup;if(slot!="hat"&&slot!="skin")throw new Exception("Unsupported cosmetic slot");if(!Active)Snapshot();string beforePrefs=prefs(),beforeEquipped=Equipped();try{selectedSlots[slot]=-1;Call(cat,"ClearItemSlot",slot);CaptureExpected(slot);if(prefs()!=beforePrefs||Equipped()!=beforeEquipped)throw new Exception("Authoritative state changed");log("cleared slot="+slot+" ownershipChanged=0");}catch{Disable();throw;}finally{float elapsedMs=(Time.realtimeSinceStartup-start)*1000f;if(elapsedMs>4f&&AutoCat.Diagnostics.Diag.Enabled(AutoCat.Diagnostics.LogLevel.Debug))log("clear slow: slot="+slot+" elapsedMs="+elapsedMs.ToString("F2",System.Globalization.CultureInfo.InvariantCulture));}}
 public void Select(int id){float start=Time.realtimeSinceStartup;object item;if(!catalog.TryGetValue(id,out item))throw new Exception("Unknown cosmetic ID");float validateStart=Time.realtimeSinceStartup;ValidateAssets(item);float validateMs=(Time.realtimeSinceStartup-validateStart)*1000f;string slot=Field(item,"ItemSlot").ToString();int prior;if(selectedSlots.TryGetValue(slot,out prior)&&prior==id){Maintain();return;}if(!Active)Snapshot();string beforePrefs=prefs(),beforeEquipped=Equipped();try{selected=id;Call(cat,"SetItem",item,false);selectedSlots[slot]=id;CaptureExpected(slot);if(prefs()!=beforePrefs||Equipped()!=beforeEquipped)throw new Exception("Authoritative state changed");log("preview id="+id.ToString()+" changedVisuals=1 ownershipChanged=0");}catch{Disable();throw;}finally{float totalMs=(Time.realtimeSinceStartup-start)*1000f;if(totalMs>4f&&AutoCat.Diagnostics.Diag.Enabled(AutoCat.Diagnostics.LogLevel.Debug))log("select slow: id="+id.ToString()+" slot="+slot+" totalMs="+totalMs.ToString("F2",System.Globalization.CultureInfo.InvariantCulture)+" validateMs="+validateMs.ToString("F2",System.Globalization.CultureInfo.InvariantCulture));}}
 public void AdoptAuthoritative(string slot){selectedSlots.Remove(slot);expected.Remove(slot);if(selectedSlots.Count==0){selected=-1;restore.Clear();originalPrefs=null;originalEquipped=null;}log("adopted authoritative slot="+slot);}
 void CaptureExpected(string slot){var checks=new List<Func<bool>>();if(slot=="skin"){foreach(var name in new[]{"_catNormal","_catLeft","_catNormalFront","_catRightFront"}){var field=cat.GetType().GetField(name,Flags);var value=field.GetValue(cat);checks.Add(()=>System.Object.ReferenceEquals(field.GetValue(cat),value));}}else{var img=Field(cat,"_hatImage");var sprite=img.GetType().GetProperty("sprite");var value=sprite.GetValue(img,null);checks.Add(()=>System.Object.ReferenceEquals(sprite.GetValue(img,null),value));var enabled=img.GetType().GetProperty("enabled");bool wasEnabled=(bool)enabled.GetValue(img,null);checks.Add(()=>(bool)enabled.GetValue(img,null)==wasEnabled);}expected[slot]=checks;}
 public void Maintain(){if(!Active)return;try{foreach(var pair in selectedSlots){bool intact=true;foreach(var check in expected[pair.Key])if(!check()){intact=false;break;}if(intact)continue;if(pair.Value<0)Call(cat,"ClearItemSlot",pair.Key);else{var item=catalog[pair.Value];ValidateAssets(item);Call(cat,"SetItem",item,false);}broadcast(pair.Key,pair.Value);CaptureExpected(pair.Key);log("maintain reapplied slot="+pair.Key+" id="+pair.Value.ToString());}}catch{Disable();throw;}}
 public void Disable(){if(!Active)return;Exception failure=null;try{bool unchanged=false;try{unchanged=Equipped()==originalEquipped;}catch(Exception e){failure=e;}if(unchanged){foreach(var action in restore)try{action();}catch(Exception e){if(failure==null)failure=e;}}else{try{Call(cat,"ClearItemSlot","hat");}catch(Exception e){if(failure==null)failure=e;}try{Call(cat,"ClearItemSlot","skin");}catch(Exception e){if(failure==null)failure=e;}try{foreach(var item in (IEnumerable)Field(cosmetics,"EquippedItems"))try{Call(cat,"SetItem",item,false);}catch(Exception e){if(failure==null)failure=e;}}catch(Exception e){if(failure==null)failure=e;}}log("restored id="+selected.ToString()+" ownershipChanged=0");if(failure!=null)throw new Exception("Renderer cleanup completed with failures",failure);}finally{selected=-1;selectedSlots.Clear();expected.Clear();restore.Clear();}}
}
}



