using System;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEngine;using UnityEngine.Events;
namespace AutocatBridge {
public sealed class NativeUnlock {
 const BindingFlags Flags=BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance|BindingFlags.Static;
 readonly DictionaryCache lookup=new DictionaryCache();readonly Dictionary<int,object> rowById=new Dictionary<int,object>();readonly Dictionary<string,List<object>> ownedRowsBySlot=new Dictionary<string,List<object>>();readonly List<object[]> ownedClicks=new List<object[]>(); readonly Assembly game;readonly CosmeticPreview visuals;readonly Action<string> log;readonly List<object[]> rows=new List<object[]>();readonly Dictionary<int,object> emotes=new Dictionary<int,object>();readonly Dictionary<string,int> selected=new Dictionary<string,int>();readonly List<int> missingEmotes=new List<int>();object inventory,donut;Type lobbyType;ulong lastLobby;IEnumerator builder;int tickCursor,ownershipCursor;public bool Loading{get{return builder!=null;}}public string Error="";public int Added{get{return rows.Count;}}
 object F(object x,string n){return lookup.Field(x.GetType(),n).GetValue(x);}object C(object x,string n,params object[] args){return lookup.Method(x.GetType(),n,args.Length).Invoke(x,args);}object S(string name,string field){return game.GetType(name,true,false).GetField(field,Flags).GetValue(null);}
 public NativeUnlock(Assembly assembly,CosmeticPreview renderer,Action<string> logger){game=assembly;visuals=renderer;log=logger;inventory=S("BongoCat.CatInventory","Instance");donut=S("EmoteDonut","Instance");lobbyType=Assembly.Load("Heathen.Steamworks").GetType("Heathen.SteamworksIntegration.LobbyData",true,false);if(!(bool)F(inventory,"IsInitialized"))throw new Exception("Inventory not ready");PruneDeadWheel();builder=BuildRows();} IEnumerator BuildRows(){var dict=(IDictionary)F(S("BongoCat.SteamItemIdReference","Inst"),"RuntimeItems");foreach(DictionaryEntry pair in dict){var item=pair.Value;if(item==null||(bool)C(item,"get_IsOwned"))continue;bool cosmetic=(bool)C(item,"get_IsCosmetic"),emote=(bool)C(item,"get_IsEmote")||(bool)C(item,"get_IsConsumable");if(!cosmetic&&!emote)continue;string slot=F(item,"ItemSlot").ToString();var collection=F(inventory,slot=="consumable"?"_consumableCollection":emote?"_emoteCollection":slot=="hat"?"_hatsCollection":"_skinsCollection");var list=(IList)F(collection,"_collectionItems");C(collection,"Add",item,false);var row=list[list.Count-1];rows.Add(new object[]{collection,row,item});rowById[(int)C(item,"get_Id")]=row;row.GetType().GetField("_initialized",Flags).SetValue(row,false);C(row,"OnItemUpdated");((GameObject)F(row,"_preview")).SetActive(false);var component=(Component)row;var buttonType=Assembly.Load("UnityEngine.UI").GetType("UnityEngine.UI.Button",true,false);var button=component.GetComponent(buttonType);if(button==null)throw new Exception("Native item button missing");var property=buttonType.GetProperty("onClick");var clicks=Activator.CreateInstance(property.PropertyType);UnityAction action=()=>{try{Choose(item);}catch(Exception e){Error=(e.InnerException??e).Message;AutoCat.Diagnostics.Diag.Fault("UnlockAll","selection.failed",e);}};C(clicks,"AddListener",action);property.SetValue(button,clicks,null);yield return null;}
 BindOwnedClicks();Tick();log("native entries added="+rows.Count.ToString()+" inventory quantities unchanged");} public void Advance(){if(builder==null)return;float start=Time.realtimeSinceStartup;try{for(int count=0;count<8&&Time.realtimeSinceStartup-start<0.002f;count++){if(!builder.MoveNext()){builder=null;break;}}}catch{Disable();throw;}}
 void BindOwnedClicks(){foreach(var name in new[]{"_hatsCollection","_skinsCollection"})foreach(var row in (IEnumerable)F(F(inventory,name),"_collectionItems")){var item=F(row,"SteamItem");if(item!=null&&(bool)C(item,"get_IsOwned"))BindOwnedRow(row);}}
 void BindOwnedRow(object row){var item=F(row,"SteamItem");if(item==null||!(bool)C(item,"get_IsCosmetic"))return;foreach(var bound in ownedClicks)if(System.Object.ReferenceEquals(bound[2],row))return;var buttonType=Assembly.Load("UnityEngine.UI").GetType("UnityEngine.UI.Button",true,false);var button=((Component)row).GetComponent(buttonType);if(button==null)throw new Exception("Owned item button missing");var clicks=buttonType.GetProperty("onClick").GetValue(button,null);UnityAction action=()=>{try{if(!Blocked()){string slot=F(item,"ItemSlot").ToString();int id=(int)C(item,"get_Id"),prior;bool hadVirtual=selected.TryGetValue(slot,out prior),nativeEquipped=(bool)F(item,"IsEquipped");if(InventoryHandoff.NeedsOwnedReequip(hadVirtual,prior,id,nativeEquipped)){C(S("BongoCat.CatCosmetics","Instance"),"EquipItem",item,true,true,true);nativeEquipped=(bool)F(item,"IsEquipped");if(!nativeEquipped)throw new Exception("Owned cosmetic re-equip was rejected");log("owned selection repaired id="+id.ToString()+" slot="+slot);}visuals.AdoptAuthoritative(slot);selected.Remove(slot);if(hadVirtual)RefreshBadge(prior);RefreshOwnedSlotBadges(slot);}}catch(Exception e){Error=(e.InnerException??e).Message;AutoCat.Diagnostics.Diag.Fault("UnlockAll","selection.failed",e);}};C(clicks,"AddListener",action);ownedClicks.Add(new object[]{clicks,action,row});string itemSlot=F(item,"ItemSlot").ToString();List<object> ownedRows;if(!ownedRowsBySlot.TryGetValue(itemSlot,out ownedRows)){ownedRows=new List<object>();ownedRowsBySlot[itemSlot]=ownedRows;}ownedRows.Add(row);}
 object NativeReplacement(object[] entry){int id=(int)C(entry[2],"get_Id");foreach(var row in (IEnumerable)F(entry[0],"_collectionItems")){if(System.Object.ReferenceEquals(row,entry[1]))continue;var item=F(row,"SteamItem");if(item!=null&&(int)C(item,"get_Id")==id)return row;}return null;}
 void RemoveTemporaryRow(object[] entry){rowById.Remove((int)C(entry[2],"get_Id"));foreach(var source in new[]{new object[]{entry[0],"OnInitialized"},new object[]{entry[2],"OnItemUpdated"}}){var field=source[0].GetType().GetField((string)source[1],Flags);var callbacks=(Delegate)field.GetValue(source[0]);if(callbacks!=null)foreach(var callback in callbacks.GetInvocationList())if(System.Object.ReferenceEquals(callback.Target,entry[1]))callbacks=Delegate.Remove(callbacks,callback);field.SetValue(source[0],callbacks);}((IList)F(entry[0],"_collectionItems")).Remove(entry[1]);var go=((Component)entry[1]).gameObject;go.SetActive(false);UnityEngine.Object.Destroy(go);} bool Blocked(){return (bool)C(S("BongoCat.ItemExchange","Instance"),"get_IsVisible")||(bool)C(S("Steam.TrashCan","Instance"),"get_InTrashMode");}
 public void Choose(object item){Error="";if(Blocked())return;int id=(int)C(item,"get_Id");log("selection requested id="+id.ToString()+" slot="+F(item,"ItemSlot").ToString());if((bool)C(item,"get_IsEmote")||(bool)C(item,"get_IsConsumable")){ToggleEmote(item,id,false);return;}string slot=F(item,"ItemSlot").ToString();int prior;bool clear=selected.TryGetValue(slot,out prior)&&prior==id;if(clear){visuals.Clear(slot);selected[slot]=-1;}else{visuals.Select(id);selected[slot]=id;}RefreshBadge(prior);RefreshBadge(id);RefreshOwnedSlotBadges(slot);Broadcast();log("selected native cosmetic="+id.ToString());}
 void SetRowEquippedVisual(object row,bool equipped){var badge=(Behaviour)F(row,"_equippedIcon");if(badge.enabled!=equipped)badge.enabled=equipped;var background=F(row,"_background");var color=background.GetType().GetProperty("color");color.SetValue(background,F(row,equipped?"_equippedColor":"_unequippedColor"),null);}
 void ApplyBadge(object row){var item=F(row,"SteamItem");if(item==null)return;int id=(int)C(item,"get_Id");string slot=F(item,"ItemSlot").ToString();bool equipped=emotes.ContainsKey(id)||InventoryHandoff.BadgeState((bool)F(item,"IsEquipped"),slot,id,selected);SetRowEquippedVisual(row,equipped);}
 void RefreshBadge(int id){object row;if(rowById.TryGetValue(id,out row)){ApplyBadge(row);return;}foreach(var bound in ownedClicks){row=bound[2];var item=F(row,"SteamItem");if(item!=null&&(int)C(item,"get_Id")==id){ApplyBadge(row);return;}}}
 void RefreshOwnedSlotBadges(string slot){List<object> ownedRows;if(!ownedRowsBySlot.TryGetValue(slot,out ownedRows))return;foreach(var row in ownedRows)ApplyBadge(row);}
 void RestoreOwnedBadges(){foreach(var bound in ownedClicks){var row=bound[2];var item=F(row,"SteamItem");if(item==null)continue;SetRowEquippedVisual(row,(bool)F(item,"IsEquipped"));}}
 void ToggleEmote(object item,int id,bool healing){float toggleStart=Time.realtimeSinceStartup;PruneDeadWheel();var wheel=(IDictionary)F(donut,"IDtoEmoteEntry");if(emotes.ContainsKey(id)){var entry=emotes[id];RemoveEmoteEntry(wheel,id,entry);emotes.Remove(id);C(donut,"RearrangeEmotes");RefreshBadge(id);LogToggleSlow(toggleStart,id,"remove");return;}if(wheel.Contains(id))return;if(wheel.Count>=Convert.ToInt32(F(donut,"maxEmoteCount")))throw new Exception("Emote wheel full: remove an emote first");var copy=(Component)UnityEngine.Object.Instantiate((UnityEngine.Object)F(donut,"emoteEntryPrefab"));try{copy.transform.SetParent((Transform)F(donut,"emoteEntryParent"),false);if((bool)C(item,"get_IsConsumable"))InitConsumable(copy,item);else C(copy,"SetItem",item,F(donut,"emoteSpawner"),donut);wheel.Add(id,copy);emotes.Add(id,copy);copy.gameObject.SetActive((bool)F(donut,"_isOpen"));C(donut,"RearrangeEmotes");if(!healing)log("temporary emote="+id.ToString());RefreshBadge(id);LogToggleSlow(toggleStart,id,"add");}catch{RemoveEmoteEntry(wheel,id,copy);emotes.Remove(id);throw;}}
 void LogToggleSlow(float start,int id,string action){float elapsedMs=(Time.realtimeSinceStartup-start)*1000f;if(elapsedMs>4f&&AutoCat.Diagnostics.Diag.Enabled(AutoCat.Diagnostics.LogLevel.Debug))log("toggle slow: action="+action+" id="+id.ToString()+" elapsedMs="+elapsedMs.ToString("F2",System.Globalization.CultureInfo.InvariantCulture));}
 void PruneDeadWheel(){if(donut==null)return;var wheel=(IDictionary)F(donut,"IDtoEmoteEntry");var dead=new List<int>();foreach(DictionaryEntry pair in wheel){var entry=pair.Value as Component;if(entry==null)dead.Add((int)pair.Key);}foreach(int id in dead){wheel.Remove(id);emotes.Remove(id);}if(dead.Count>0){C(donut,"RearrangeEmotes");log("removed destroyed emote entries="+dead.Count.ToString());}} void RemoveEmoteEntry(IDictionary wheel,int id,object entry){if(wheel.Contains(id)&&System.Object.ReferenceEquals(wheel[id],entry))wheel.Remove(id);var component=entry as Component;if(component!=null)UnityEngine.Object.Destroy(component.gameObject);} void InitConsumable(Component entry,object item){var type=entry.GetType();type.GetField("_steamItem",Flags).SetValue(entry,item);type.GetField("_emoteSpawner",Flags).SetValue(entry,F(donut,"emoteSpawner"));type.GetField("_emoteDonut",Flags).SetValue(entry,donut);var image=F(entry,"image");image.GetType().GetProperty("sprite").SetValue(image,F(item,"Icon"),null);((GameObject)F(entry,"counter")).SetActive(false);var buttonType=Assembly.Load("UnityEngine.UI").GetType("UnityEngine.UI.Button",true,false);var button=entry.GetComponent(buttonType);if(button==null)throw new Exception("Consumable wheel button missing");var property=buttonType.GetProperty("onClick");var clicks=Activator.CreateInstance(property.PropertyType);UnityAction action=()=>{try{C(F(donut,"emoteSpawner"),"SpawnEmoteParticle",item);game.GetType("BongoCat.Multiplayer.SteamMultiplayer",true,false).GetMethod("SendEmote",Flags).Invoke(null,new[]{item});log("consumable playback; quantity unchanged; id="+C(item,"get_Id").ToString());}catch(Exception e){log("consumable playback failed: "+(e.InnerException??e).Message);}};C(clicks,"AddListener",action);property.SetValue(button,clicks,null);}
 void Broadcast(){var lobby=lobbyType.GetField("Current",Flags).GetValue(null);if(!(bool)C(lobby,"get_IsValid"))return;foreach(var pair in selected)C(lobby,pair.Key=="hat"?"set_MyHat":"set_MySkin",pair.Value);}
 // CosmeticPreview.Maintain() re-applies the LOCAL visual whenever the game resets it, but has no access to the lobby broadcast -- without this, a remote observer never learns the temporary item survived, only the local client does. Called from CosmeticPreview via the broadcast delegate passed at construction.
 public void BroadcastSlot(string slot,int id){RefreshOwnedSlotBadges(slot);var lobby=lobbyType.GetField("Current",Flags).GetValue(null);if(!(bool)C(lobby,"get_IsValid"))return;C(lobby,slot=="hat"?"set_MyHat":"set_MySkin",id);}
 // The same periodic reset that CosmeticPreview.Maintain() catches for hat/skin (observed recurring on an exact ~120s cadence in live logs) plausibly also wipes temporary wheel entries -- unlike hat/skin, nothing previously re-added a wiped temporary emote. Re-adds any tracked temporary emote whose wheel key has vanished entirely (a value replaced/destroyed in place is left to PruneDeadWheel, not re-created here, since we can't tell that apart from a legitimate removal).
 void HealWheel(){if(donut==null)return;var wheel=(IDictionary)F(donut,"IDtoEmoteEntry");missingEmotes.Clear();foreach(var pair in emotes)if(!wheel.Contains(pair.Key))missingEmotes.Add(pair.Key);PruneDeadWheel();foreach(int id in missingEmotes){emotes.Remove(id);object row;if(!rowById.TryGetValue(id,out row))continue;var item=F(row,"SteamItem");if(item==null)continue;try{ToggleEmote(item,id,true);log("wheel entry healed id="+id.ToString());}catch(Exception e){log("wheel heal failed id="+id.ToString()+" error="+(e.InnerException??e).Message);}}}
 public void Tick(){
  float tickStart=Time.realtimeSinceStartup;
  int retired=InventoryHandoff.ReconcileSlice(rows,ref ownershipCursor,32,item=>(bool)C(item,"get_IsOwned"),NativeReplacement,BindOwnedRow,RemoveTemporaryRow);
  if(retired>0)log("acquired items: retired temporary rows="+retired.ToString());
  if(emotes.Count>0)HealWheel();
  float reconcileMs=(Time.realtimeSinceStartup-tickStart)*1000f;
  bool hide=Blocked();
  // Bounded like BuildRows/Advance: an unbounded per-row reflection sweep here (previously every row, every Tick) is a per-tick main-thread cost that scales with catalog size and was suspected to cause UI stalls while scrolling. Round-robin a time-boxed slice instead of touching every row every call.
  int processed=0;
  if(rows.Count>0){
   if(tickCursor>=rows.Count)tickCursor=0;
   int start=tickCursor;float sliceStart=Time.realtimeSinceStartup;
   do{
    var entry=rows[tickCursor];var row=entry[1];var item=entry[2];
    var icon=F(row,"_itemImage");var sprite=icon.GetType().GetProperty("sprite");var expected=F(item,"Icon");if(!System.Object.ReferenceEquals(sprite.GetValue(icon,null),expected)){sprite.SetValue(icon,expected,null);log("icon corrected id="+C(item,"get_Id").ToString());}
    var counter=(GameObject)F(row,"_counterIndicator");if(counter.activeSelf)counter.SetActive(false);
    int itemId=(int)C(item,"get_Id");string slot=F(item,"ItemSlot").ToString();bool equipped=emotes.ContainsKey(itemId)||InventoryHandoff.BadgeState(false,slot,itemId,selected);
    var badge=(Behaviour)F(row,"_equippedIcon");if(badge.enabled!=equipped)badge.enabled=equipped;
    var go=((Component)row).gameObject;if(go.activeSelf==hide)go.SetActive(!hide);
    var disabled=(Behaviour)F(row,"_disabledOverlay");if(disabled.enabled)disabled.enabled=false;var unowned=(Behaviour)F(row,"_unownedOverlay");if(unowned.enabled)unowned.enabled=false;
    tickCursor=(tickCursor+1)%rows.Count;processed++;
   }while(tickCursor!=start&&Time.realtimeSinceStartup-sliceStart<0.0015f);
  }
  var lobby=lobbyType.GetField("Current",Flags).GetValue(null);ulong id=(ulong)F(lobby,"_id");if(id!=lastLobby){lastLobby=id;if(selected.Count>0)Broadcast();}
  float totalMs=(Time.realtimeSinceStartup-tickStart)*1000f;
  if(totalMs>16.7f&&AutoCat.Diagnostics.Diag.Current!=null)AutoCat.Diagnostics.Diag.Current.LimitedValues(AutoCat.Diagnostics.LogLevel.Warn,"UnlockAll","maintenance.latency","totalUs={0} reconcileUs={1} rows={2} processed={3}",(long)(totalMs*1000),(long)(reconcileMs*1000),rows.Count,processed);
  if(totalMs>3f&&AutoCat.Diagnostics.Diag.Enabled(AutoCat.Diagnostics.LogLevel.Debug))log("tick slow: totalMs="+totalMs.ToString("F2",System.Globalization.CultureInfo.InvariantCulture)+" reconcileMs="+reconcileMs.ToString("F2",System.Globalization.CultureInfo.InvariantCulture)+" rows="+rows.Count.ToString()+" processed="+processed.ToString());
 }
 public void Disable(){builder=null;Exception failure=null;foreach(var binding in ownedClicks)try{C(binding[0],"RemoveListener",binding[1]);}catch(Exception e){if(failure==null)failure=e;}foreach(var entry in rows)try{RemoveTemporaryRow(entry);}catch(Exception e){if(failure==null)failure=e;}rows.Clear();if(donut!=null){IDictionary wheel=null;try{wheel=(IDictionary)F(donut,"IDtoEmoteEntry");}catch(Exception e){if(failure==null)failure=e;}if(wheel!=null)foreach(var pair in emotes)try{RemoveEmoteEntry(wheel,pair.Key,pair.Value);}catch(Exception e){if(failure==null)failure=e;}emotes.Clear();try{C(donut,"RearrangeEmotes");}catch(Exception e){if(failure==null)failure=e;}}try{visuals.Disable();}catch(Exception e){if(failure==null)failure=e;}if(selected.Count>0)try{var normal=S("BongoCat.CatCosmetics","Instance");var slots=new List<string>(selected.Keys);foreach(var slot in slots){selected[slot]=-1;foreach(var item in (IEnumerable)F(normal,"EquippedItems"))if(F(item,"ItemSlot").ToString()==slot)selected[slot]=(int)C(item,"get_Id");}Broadcast();}catch(Exception e){if(failure==null)failure=e;}try{RestoreOwnedBadges();}catch(Exception e){if(failure==null)failure=e;}finally{selected.Clear();ownedClicks.Clear();ownedRowsBySlot.Clear();}log("native unlock disabled; temporary entries removed");if(failure!=null)throw new Exception("Native unlock cleanup completed with failures",failure);}
}
}






