using System;using System.IO;using System.Reflection;using System.Collections;using System.Collections.Generic;using UnityEngine;using AutoCat.Diagnostics;
namespace AutocatBridge {
 public sealed partial class Worker {
  DiagnosticLog diagnostics=new DiagnosticLog("game");string diagnosticFolder,diagnosticSession="";float diagnosticAt,traceAt,repairFlushAt;int diagnosticEmotes,diagnosticPolls,giftRequestId,repairCosmetics,repairEmotes;int lastReadiness=-1;string lastDiagnosticProblem="";bool diagnosticThrottled;
  void DiagnosticStartup(){diagnosticFolder=Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location),"autocat-data/logs");Diag.Current=diagnostics;diagnostics.Write(LogLevel.Info,"Runtime","initialized","runtime=100 source=Assembly-CSharp; update=per-frame; statePollMs=100; nativeTickMs=500");}
  void ConfigureDiagnostics(string id,int level){if(!DiagnosticLog.ValidSession(id)||level<0||level>4)throw new ArgumentException("Invalid diagnostic configuration");if(diagnosticSession!=""&&diagnosticSession!=id){diagnostics.Write(LogLevel.Info,"Session","handoff","New external diagnostic session");diagnostics.Dispose();diagnostics=new DiagnosticLog("game");Diag.Current=diagnostics;}diagnostics.Configure(diagnosticFolder,id,(LogLevel)level);diagnosticSession=id;Diag.Level=(LogLevel)level;diagnostics.Values(LogLevel.Info,"Session","linked","runtime=100 pid={0} level={1} source=game-component",GetCurrentProcessId(),level);}
  void NativeLog(string message){LogLevel level=message.IndexOf("failed",StringComparison.OrdinalIgnoreCase)>=0?LogLevel.Error:message.IndexOf("slow:",StringComparison.Ordinal)>=0?LogLevel.Debug:LogLevel.Info;string action="state";if(message.StartsWith("tick slow:"))action="maintenance.duration";else if(message.StartsWith("maintain reapplied")){action="state.reapplied";repairCosmetics++;if(repairFlushAt==0)repairFlushAt=Time.realtimeSinceStartup+1;}else if(message.StartsWith("wheel entry healed")){action="emote.restored";repairEmotes++;if(repairFlushAt==0)repairFlushAt=Time.realtimeSinceStartup+1;}else if(message.StartsWith("restored"))action="visuals.restored";else if(message.StartsWith("acquired items:"))action="ownership.reconciled";else if(message.StartsWith("native entries added="))action="activation.applied";else if(message.StartsWith("native unlock disabled"))action="disabled.restored";else if(message.StartsWith("selection requested"))action="selection.requested";else if(message.StartsWith("preview id="))action="selection.applied";else if(message.StartsWith("cleared slot="))action="selection.cleared";
   if((action=="state.reapplied"||action=="emote.restored")&&!diagnostics.Enabled(LogLevel.Debug))return;
   if(diagnostics.Enabled(level)){if(level>=LogLevel.Warn)diagnostics.Limited(level,"UnlockAll",action,message);else diagnostics.Write(level,"UnlockAll",action,message);}}
  void FlushRepairDiagnostics(bool force){if(repairCosmetics==0&&repairEmotes==0)return;if(!force&&Time.realtimeSinceStartup<repairFlushAt)return;diagnostics.Values(LogLevel.Info,"UnlockAll","repair.summary","cosmetics={0} emotes={1}; authoritative refresh healed",repairCosmetics,repairEmotes);repairCosmetics=repairEmotes=0;repairFlushAt=0;}
  void DiagnosticState(bool normalReady,bool emoteReady,int lifetime){try{diagnosticPolls++;float now=Time.realtimeSinceStartup;int ready=(normalReady?1:0)|(emoteReady?2:0);if(ready!=lastReadiness){diagnostics.Values(LogLevel.Info,"Gifts","readiness.changed","normalReady={0} emoteReady={1} source=game-derived-state",normalReady?1:0,emoteReady?1:0);lastReadiness=ready;}
   if(problem!=lastDiagnosticProblem){diagnostics.Write(problem==""?LogLevel.Info:LogLevel.Warn,"Runtime",problem==""?"condition.cleared":"condition",problem);lastDiagnosticProblem=problem;}
   bool throttled=running&&((emoting&&emoteBudget<emoteRate-0.01f)||tapScale<0.99f);if(throttled!=diagnosticThrottled){diagnostics.Values(throttled?LogLevel.Warn:LogLevel.Info,"Performance",throttled?"throttle.active":"throttle.recovered","emoteBudget={0} tapScalePermille={1} frameAvgUs={2}",(long)emoteBudget,(long)(tapScale*1000),(long)(frameAverage*1000000));diagnosticThrottled=throttled;}
   if(now>=diagnosticAt){diagnostics.Values(LogLevel.Info,"Emotes","summary","callsDelta={0} callsTotal={1} requestedRate={2} cachedTotal={3}",emoteCalls-diagnosticEmotes,emoteCalls,emoteRate,emoteTotal);diagnostics.Values(LogLevel.Debug,"Polling","summary","iterations={0} lifetime={1} source=process-memory",diagnosticPolls,lifetime);diagnosticEmotes=emoteCalls;diagnosticPolls=0;diagnosticAt=now+30;}
   if(diagnostics.Enabled(LogLevel.Trace)&&now>=traceAt){diagnostics.Values(LogLevel.Trace,"Polling","sample","lifetime={0} frameAvgUs={1} framePeakUs={2}",lifetime,(long)(frameAverage*1000000),(long)(framePeak*1000000));traceAt=now+1;}
   FlushRepairDiagnostics(false);PollExchangeDiagnostic(now);
  }catch(Exception e){diagnostics.Fault("Diagnostics","observation.failed",e);}}
  sealed class ExchangeObservation {public long Id;public int Before,Expected;public bool BeforeValid,Completed;public float Deadline,Next;public IEnumerator Routine;public FieldInfo Closure;public object[] Items;public long[] Quantities;}
  readonly List<ExchangeObservation> exchangeObservations=new List<ExchangeObservation>();long exchangeId;
  bool TryExchangeStat(out int value){value=0;try{var type=Assembly.Load("Heathen.Steamworks").GetType("Heathen.SteamworksIntegration.API.StatsAndAchievements+Client",true,false);var method=type.GetMethod("GetStat",BindingFlags.Public|BindingFlags.Static,null,new[]{typeof(string),typeof(int).MakeByRefType()},null);object[] args={"Exchanges",0};bool ok=(bool)method.Invoke(null,args);value=(int)args[1];return ok;}catch{return false;}}
  ExchangeObservation ObserveExchangeStart(IEnumerator routine,IList items,int expected){try{if(exchangeObservations.Count>=16){diagnostics.Limited(LogLevel.Warn,"Exchange","observation.backlog","Further outcomes cannot be tracked; bounded at 16 requests");return null;}var observation=new ExchangeObservation{Id=++exchangeId,Expected=expected,Routine=routine,Deadline=Time.realtimeSinceStartup+60,Items=new object[items.Count],Quantities=new long[items.Count]};observation.BeforeValid=TryExchangeStat(out observation.Before);
   foreach(var field in routine.GetType().GetFields(BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance))if(field.FieldType.GetField("errored",BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance)!=null&&field.FieldType.GetField("exchangeCompleted",BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance)!=null){observation.Closure=field;break;}
   for(int i=0;i<items.Count;i++){observation.Items[i]=items[i];observation.Quantities[i]=(long)Call(Field(items[i],"RuntimeData"),"GetTotalQuantity");if(diagnostics.Enabled(LogLevel.Debug))diagnostics.Values(LogLevel.Debug,"Exchange","input.observed","request={0} itemId={1} quantity={2}",observation.Id,(int)Call(items[i],"get_Id"),observation.Quantities[i]);}
   exchangeObservations.Add(observation);diagnostics.Values(LogLevel.Info,"Exchange","request.started","request={0} expectedExchanges={1} inputDefinitions={2} cachedSuccessBefore={3}",observation.Id,expected,items.Count,observation.BeforeValid?observation.Before:-1);return observation;
  }catch(Exception e){diagnostics.Fault("Exchange","observation.start.failed",e);return null;}}
  void ObserveExchangeEnd(ExchangeObservation o){if(o==null)return;o.Completed=true;diagnostics.Values(LogLevel.Info,"Exchange","routine.ended","request={0}; awaiting observed result; coroutine end alone is not success",o.Id);}
  void PollExchangeDiagnostic(float now){for(int i=exchangeObservations.Count-1;i>=0;i--){var o=exchangeObservations[i];if(now<o.Next)continue;o.Next=now+1;int after;bool statValid=TryExchangeStat(out after);bool error=false,callbackDone=false,closureKnown=false;if(o.Closure!=null){var closure=o.Closure.GetValue(o.Routine);if(closure!=null){var flags=BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic;error=(bool)closure.GetType().GetField("errored",flags).GetValue(closure);callbackDone=(bool)closure.GetType().GetField("exchangeCompleted",flags).GetValue(closure);closureKnown=true;}}
    bool expired=now>=o.Deadline;if(!o.Completed&&!error&&!expired)continue;long consumed=0;foreach(var item in o.Items){int index=Array.IndexOf(o.Items,item);long quantity=(long)Call(Field(item,"RuntimeData"),"GetTotalQuantity");consumed+=Math.Max(0,o.Quantities[index]-quantity);}
    int delta=statValid&&o.BeforeValid?after-o.Before:-1;bool confirmed=o.Completed&&closureKnown&&callbackDone&&!error&&delta>=o.Expected&&consumed>0;
    if(!confirmed&&!error&&!expired)continue;if(confirmed)trades+=o.Expected;diagnostics.Values(confirmed?LogLevel.Info:LogLevel.Warn,"Exchange",confirmed?"result.confirmed":error?"result.failed":"result.unverified","request={0} gameSuccessDelta={1} consumedObserved={2} expected={3}; source=game-callback-flags+Steam-cache; concurrent manual activity can affect deltas",o.Id,delta,consumed,o.Expected);exchangeObservations.RemoveAt(i);
   }}
 }
}
