using System;using System.IO;using System.IO.Pipes;using System.Text;using System.Threading;using System.Diagnostics;using System.Xml.Serialization;using AutoCat.Diagnostics;
public class Settings {
 public int Taps=10,MenuKey=45,PauseKey=36,MenuModifiers,PauseModifiers;
 public bool Clicker,Gifts,Exchange,Emoting,InstaGift,ExtremeRates; public int EmoteRate=10;
 public void Validate(){EmoteRate=Math.Max(1,Math.Min(ExtremeRates?RatePolicy.EmoteMaximum:RatePolicy.NormalEmoteMaximum,EmoteRate));Taps=Math.Max(1,Math.Min(ExtremeRates?TapEngine.MaximumRate:RatePolicy.NormalClickMaximum,Taps));if(MenuKey<0||MenuKey>259)MenuKey=45;if(PauseKey<0||PauseKey>259)PauseKey=36;MenuModifiers&=15;PauseModifiers&=15;}
 public static Settings Read(string path){try{using(var f=File.OpenRead(path)){var s=(Settings)new XmlSerializer(typeof(Settings)).Deserialize(f);int oldTaps=s.Taps,oldEmotes=s.EmoteRate;s.Validate();Diag.Values(LogLevel.Info,"Settings","loaded","source=settings.xml taps={0} emoteRate={1} priorTaps={2} priorEmoteRate={3}",s.Taps,s.EmoteRate,oldTaps,oldEmotes);return s;}}catch(FileNotFoundException){Diag.Write(LogLevel.Info,"Settings","defaults","No saved configuration");return new Settings();}catch(DirectoryNotFoundException){Diag.Write(LogLevel.Info,"Settings","defaults","No saved configuration directory");return new Settings();}catch(Exception e){Diag.Fault("Settings","load.failed.defaults",e);return new Settings();}}
 public void Save(string path){var safe=(Settings)MemberwiseClone();safe.Validate();Diag.Values(LogLevel.Info,"Settings","save.requested","source=settings.xml taps={0} emoteRate={1} extreme={2}",safe.Taps,safe.EmoteRate,safe.ExtremeRates?1:0);long start=Stopwatch.GetTimestamp();try{Directory.CreateDirectory(Path.GetDirectoryName(path));string temp=path+".tmp";using(var f=File.Create(temp))new XmlSerializer(typeof(Settings)).Serialize(f,safe);if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);}catch(Exception e){Diag.Fault("Settings","save.failed",e);throw;}
  if(Diag.Current!=null)try{Settings read;using(var f=File.OpenRead(path))read=(Settings)new XmlSerializer(typeof(Settings)).Deserialize(f);bool equal=true;foreach(var field in typeof(Settings).GetFields())if(!Object.Equals(field.GetValue(safe),field.GetValue(read)))equal=false;Diag.Values(equal?LogLevel.Info:LogLevel.Error,"Settings",equal?"save.verified":"save.verification.failed","source=settings.xml elapsedMs={0}",(Stopwatch.GetTimestamp()-start)*1000/Stopwatch.Frequency);}catch(Exception e){Diag.Fault("Settings","readback.failed",e);}
 }
}
// Only confirmed permission is saved; a pending confirmation never grants access.
sealed class RatePolicy {
 public const int NormalClickMaximum=200,NormalEmoteMaximum=100,EmoteMaximum=100000000;
 public bool Enabled{get;private set;}public bool Pending{get;private set;}
 public void Restore(bool confirmed){Enabled=confirmed;Pending=false;}
 public void Request(bool value){if(!value){Enabled=false;Pending=false;}else if(!Enabled)Pending=true;}
 public void Confirm(){if(Pending){Enabled=true;Pending=false;}}
 public int Clamp(int rate,bool emote){return Math.Max(1,Math.Min(Enabled?(emote?EmoteMaximum:TapEngine.MaximumRate):(emote?NormalEmoteMaximum:NormalClickMaximum),rate));}
}
sealed class TapEngine:IDisposable {
 public const int MaximumRate=100000000;public const long CounterCeiling=2000000000;
 readonly string pipeName;readonly object gate=new object();Thread worker;NamedPipeServerStream pipe;volatile bool closed;
 public volatile float PerformanceScale=1;public volatile bool Enabled;public volatile int Rate=1000;public volatile string Status="waiting";public long Sent;
 long remaining;long observed;bool initialized;int wake;string loggedStatus="";long lastSummary,lastSent;
 public TapEngine(string name="BongoCatxTheFarmerWasReplaced"){pipeName=name;}
 public long Remaining {get{lock(gate)return remaining;}}
 public void QueueWakeup(){Interlocked.Exchange(ref wake,1);}
 public void Observe(int total,int lifetime){lock(gate){if(total<0||lifetime<0){initialized=false;return;}long allowed=Math.Max(0,CounterCeiling-Math.Max(total,lifetime));remaining=initialized?Math.Min(remaining,allowed):allowed;initialized=true;observed=Stopwatch.GetTimestamp();}}
 public void ResetGuard(){lock(gate){initialized=false;remaining=0;}}
 public static int Grant(int requested,long budget){return (int)Math.Max(0,Math.Min(Math.Max(0,requested),budget));}
 public void Start(){if(worker!=null)return;Diag.Write(LogLevel.Info,"Clicks","transport.start","batched intervalMs=100; no individual tap logging");worker=new Thread(Run);worker.IsBackground=true;worker.Start();}
 static readonly byte[] ZeroFrame=Frame("0");
 public static byte[] Frame(string s){var b=Encoding.Unicode.GetBytes(s);var a=new byte[b.Length+2];a[0]=(byte)(b.Length>>8);a[1]=(byte)b.Length;Buffer.BlockCopy(b,0,a,2,b.Length);return a;}
 void Run(){while(!closed){try{using(var p=new NamedPipeServerStream(pipeName,PipeDirection.InOut,1,PipeTransmissionMode.Byte,PipeOptions.Asynchronous)){
  lock(gate){if(closed)return;pipe=p;}Status="waiting for game";var wait=p.BeginWaitForConnection(null,null);using(wait.AsyncWaitHandle){while(!closed&&!wait.AsyncWaitHandle.WaitOne(200)){}if(closed)return;p.EndWaitForConnection(wait);}
  var timer=Stopwatch.StartNew();long last=timer.ElapsedMilliseconds;double fraction=0;lastSummary=0;lastSent=Interlocked.Read(ref Sent);
  while(!closed&&p.IsConnected){Thread.Sleep((int)(100/Math.Max(0.2f,PerformanceScale)));long now=timer.ElapsedMilliseconds;int count=0;
   lock(gate){bool fresh=initialized&&(Stopwatch.GetTimestamp()-observed)/(double)Stopwatch.Frequency<2;
    if(Enabled&&fresh&&remaining>0){fraction+=Math.Min(0.25,(now-last)/1000.0)*Math.Max(1,Math.Min(MaximumRate,Rate))*Math.Max(0,Math.Min(1,PerformanceScale));int request=(int)fraction;count=Grant(request,remaining);fraction-=request;remaining-=count;Status="connected";}
    else{fraction=0;Status=!Enabled?"connected":!fresh?"waiting for live counter":remaining<=0?"counter cutoff reached":"paused";}
    if(Interlocked.Exchange(ref wake,0)!=0&&count==0&&(!initialized||remaining>0)){count=1;if(initialized)remaining--;}
   }
   if(Status!=loggedStatus){loggedStatus=Status;Diag.Write(LogLevel.Info,"Clicks","transport.state",Status);}if(now-lastSummary>=30000){long sent=Interlocked.Read(ref Sent);Diag.Values(LogLevel.Info,"Clicks","summary","windowMs={0} sentDelta={1} sentTotal={2} requestedRate={3}",now-lastSummary,sent-lastSent,sent,Rate);lastSummary=now;lastSent=sent;}if(Diag.Enabled(LogLevel.Trace)&&count>0&&now%1000<110)Diag.Values(LogLevel.Trace,"Clicks","batch.sample","batchCount={0}",count);
   last=now;var frame=count==0?ZeroFrame:Frame(count.ToString(System.Globalization.CultureInfo.InvariantCulture));var write=p.BeginWrite(frame,0,frame.Length,null,null);
   using(write.AsyncWaitHandle){if(!write.AsyncWaitHandle.WaitOne(1000))throw new IOException("Tap connection timed out");p.EndWrite(write);}Interlocked.Add(ref Sent,count);
  }
 }}catch(Exception e){if(!closed){if(BridgeClient.PipeDisconnected(e)){Status="waiting for game";Diag.CurrentLimited("Clicks","transport.disconnected","Game tap connection closed; waiting to reconnect");}else{Status=e.Message;Diag.Fault("Clicks","transport.failed",e);}}}finally{lock(gate){pipe=null;}}if(!closed)Thread.Sleep(750);}}
 public void Dispose(){closed=true;Enabled=false;lock(gate){if(pipe!=null)pipe.Dispose();}bool drained=worker==null||worker.Join(1500);Diag.Values(drained?LogLevel.Info:LogLevel.Warn,"Clicks","transport.stop","threadJoined={0} sentTotal={1}",drained?1:0,Interlocked.Read(ref Sent));}
}
sealed class GameState {
 public long NormalTokens=-1,EmoteTokens=-1;public float PerformanceScale=1;public double FrameMs,PeakMs,EmoteBudget;public int EmoteTotal=-1,EmoteCalls;public bool Ready;public int Total,Lifetime,Spent,NormalTimer,EmoteTimer,Possible,Claims,Exchanges;public bool NormalReady,EmoteReady;public string Message="waiting for game";public DateTime At=DateTime.UtcNow;
 public static GameState Parse(string line){var s=new GameState();if(line==null)return s;var p=line.Split('|');if(p.Length>=12&&p[0]=="OK"){
  s.Total=int.Parse(p[1]);s.Lifetime=int.Parse(p[2]);s.Spent=int.Parse(p[3]);s.NormalReady=p[4]=="1";s.EmoteReady=p[5]=="1";s.NormalTimer=int.Parse(p[6]);s.EmoteTimer=int.Parse(p[7]);s.Possible=int.Parse(p[8]);s.Claims=int.Parse(p[9]);s.Exchanges=int.Parse(p[10]);s.Message=Encoding.UTF8.GetString(Convert.FromBase64String(p[11]));if(p.Length>=14){s.EmoteTotal=int.Parse(p[12]);s.EmoteCalls=int.Parse(p[13]);}if(p.Length>=18){s.PerformanceScale=float.Parse(p[14],System.Globalization.CultureInfo.InvariantCulture);s.FrameMs=double.Parse(p[15],System.Globalization.CultureInfo.InvariantCulture);s.PeakMs=double.Parse(p[16],System.Globalization.CultureInfo.InvariantCulture);s.EmoteBudget=double.Parse(p[17],System.Globalization.CultureInfo.InvariantCulture);}if(p.Length>=20){s.NormalTokens=long.Parse(p[18]);s.EmoteTokens=long.Parse(p[19]);}s.Ready=s.Total>=0&&s.Lifetime>=0;
 }else if(p.Length>1&&p[0]=="ERROR")s.Message=Encoding.UTF8.GetString(Convert.FromBase64String(p[1]));return s;}
}
sealed class BridgeClient:IDisposable {
 readonly string dll;readonly TapEngine taps;Thread worker;volatile bool closed;NamedPipeClientStream pipe;readonly object gate=new object();
 public volatile string CosmeticCatalog="";public volatile bool CatalogRequested;int previewPending=int.MinValue;public void PreviewCosmetic(int id){Interlocked.Exchange(ref previewPending,id);}public volatile bool UnlockAll;public volatile bool Running,Gifts,Exchange,Emoting,InstaGift;public volatile int EmoteRate=1;public volatile GameState State=new GameState();public volatile string Connection="waiting for game";
 public BridgeClient(string path,TapEngine engine){dll=path;taps=engine;}
 public void Start(){worker=new Thread(Loop);worker.IsBackground=true;worker.Start();}
 static string ReadLineBounded(StreamReader reader){var task=reader.ReadLineAsync();if(!task.Wait(2500))throw new IOException("Bridge response timed out");return task.Result;}
 static void LogState(GameState next,ref GameState prior,ref long summary){long now=Stopwatch.GetTimestamp();if(prior==null||prior.Ready!=next.Ready)Diag.Write(LogLevel.Info,"State",next.Ready?"ready":"unavailable","source=game-component observation; persistence unverified");if(next.Ready){if(prior==null||!prior.Ready||next.Lifetime<prior.Lifetime)Diag.Values(prior==null||!prior.Ready?LogLevel.Info:LogLevel.Warn,"LifetimeTaps",prior==null||!prior.Ready?"observed":"decreased","source=process-memory prior={0} observed={1}; no reset performed by diagnostics",prior==null||!prior.Ready?-1:prior.Lifetime,next.Lifetime);
   if(prior==null||prior.NormalTokens!=next.NormalTokens||prior.EmoteTokens!=next.EmoteTokens)Diag.Values(LogLevel.Info,"Gifts","tokens.observed","source=Steam-inventory-cache normalBefore={0} normalAfter={1} emoteBefore={2} emoteAfter={3}",prior==null?-1:prior.NormalTokens,next.NormalTokens,prior==null?-1:prior.EmoteTokens,next.EmoteTokens);
   if(prior==null||prior.Message!=next.Message)Diag.Write(String.IsNullOrEmpty(next.Message)?LogLevel.Info:LogLevel.Warn,"State",String.IsNullOrEmpty(next.Message)?"condition.cleared":"condition",next.Message);
   if(now-summary>=30*Stopwatch.Frequency){Diag.Values(LogLevel.Info,"State","summary","source=process-memory lifetime={0} gained={1} spent={2} emotesCached={3}",next.Lifetime,next.Total,next.Spent,next.EmoteTotal);Diag.Values(LogLevel.Info,"Performance","summary","frameAvgUs={0} framePeakUs={1} tapScalePermille={2} emoteBudget={3}",(long)(next.FrameMs*1000),(long)(next.PeakMs*1000),(long)(next.PerformanceScale*1000),(long)next.EmoteBudget);summary=now;}
  }prior=next;}
 internal static bool StartupNotReady(Exception error){string message=(error.InnerException??error).Message;return message.IndexOf("Input hook not initialized",StringComparison.OrdinalIgnoreCase)>=0||message.IndexOf("Bongo Cat not initialized",StringComparison.OrdinalIgnoreCase)>=0;}
 internal static bool PipeDisconnected(Exception error){var root=error.InnerException??error;if(!(root is IOException))return false;string message=root.Message;return message.IndexOf("pipe is broken",StringComparison.OrdinalIgnoreCase)>=0||message.IndexOf("pipe has been ended",StringComparison.OrdinalIgnoreCase)>=0||message.IndexOf("pipe is closed",StringComparison.OrdinalIgnoreCase)>=0||message.IndexOf("pipe has not been connected",StringComparison.OrdinalIgnoreCase)>=0;}
 void Loop(){int lastPid=0,observedPid=0;bool loaded=false,searchLogged=false;long samePidReloadAfter=0;GameState previous=null;long summaryAt=0;Diag.Write(LogLevel.Info,"Connection","polling.start","controlIntervalMs=100; processSearchMs=750");while(!closed){try{
  int pid=0;foreach(var p in Process.GetProcessesByName("BongoCat")){using(p){pid=p.Id;break;}}if(pid==0){if(!searchLogged){Diag.Values(LogLevel.Info,"Connection",lastPid==0?"searching":"process.disappeared","previousPid={0}",lastPid);searchLogged=true;}Connection="waiting for game";State=new GameState();taps.ResetGuard();lastPid=0;loaded=false;Thread.Sleep(750);continue;}
  searchLogged=false;if(pid!=lastPid){if(observedPid!=0&&observedPid!=pid)Diag.Values(LogLevel.Info,"Connection","game.restart.detected","previousPid={0} pid={1}; counter persistence not inferred",observedPid,pid);observedPid=pid;Diag.Values(LogLevel.Info,"Connection",lastPid==0?"process.found":"process.changed","pid={0} previousPid={1}",pid,lastPid);try{using(var target=Process.GetProcessById(pid)){var module=target.MainModule;string version=module==null?"":module.FileVersionInfo.FileVersion;if(String.IsNullOrEmpty(version))Diag.CurrentLimited("Connection","metadata.pending","Executable metadata is not ready; attachment will continue");else Diag.Write(LogLevel.Info,"Connection","game.metadata","fileVersion="+version+" source=executable-metadata");}}catch(Exception){var log=Diag.Current;if(log!=null)log.Limited(LogLevel.Warn,"Connection","metadata.unavailable","Executable metadata unavailable; attachment will continue");}loaded=false;lastPid=pid;taps.ResetGuard();previous=null;}
  using(var p=new NamedPipeClientStream(".","autocat-control-"+pid,PipeDirection.InOut,PipeOptions.Asynchronous)){
   lock(gate){if(closed)return;pipe=p;}
   try{p.Connect(200);}catch(TimeoutException){bool existing=loaded;if(!loaded){Connection="attaching";Diag.Values(LogLevel.Info,"Connection","attach.attempt","pid={0} method=Mono",pid);BridgeLoader.Load(pid,dll);loaded=true;taps.QueueWakeup();}else Diag.CurrentLimited("Connection","reconnect.wait","Waiting for existing component; same PID");try{p.Connect(6000);}catch(TimeoutException){if(!existing)throw;long now=Stopwatch.GetTimestamp();if(now>=samePidReloadAfter){loaded=false;samePidReloadAfter=now+10*Stopwatch.Frequency;Diag.Write(LogLevel.Warn,"Connection","same_pid.reinject","Component pipe remained unavailable; scheduling one bounded reinjection");}Connection="waiting for component";State=new GameState{Message=Connection};taps.ResetGuard();taps.PerformanceScale=0;Thread.Sleep(250);continue;}}
   Connection="attached";samePidReloadAfter=0;Diag.Values(LogLevel.Info,"Connection","attached","pid={0}",pid);using(var reader=new StreamReader(p,Encoding.UTF8,false,1024,true))using(var writer=new StreamWriter(p,new UTF8Encoding(false),1024,true)){writer.AutoFlush=true;
    if(Diag.Current!=null){writer.WriteLine(DiagnosticSession.Handshake());string response=ReadLineBounded(reader);if(response!="LOGOK")Diag.Write(LogLevel.Warn,"Logger","handshake.failed","Runtime did not accept shared diagnostic session");}
    while(!closed&&p.IsConnected){if(CatalogRequested){writer.WriteLine("CATALOG");CosmeticCatalog=ReadLineBounded(reader);CatalogRequested=false;}int choice=Interlocked.Exchange(ref previewPending,int.MinValue);if(choice!=int.MinValue){writer.WriteLine("PREVIEW|"+choice);ReadLineBounded(reader);}writer.WriteLine("SET|"+(Running?"1":"0")+"|"+(Gifts?"1":"0")+"|"+(Exchange?"1":"0")+"|"+(Emoting?"1":"0")+"|"+EmoteRate+"|"+(InstaGift?"1":"0")+"|"+(UnlockAll?"1":"0"));var next=GameState.Parse(ReadLineBounded(reader));State=next;LogState(next,ref previous,ref summaryAt);taps.PerformanceScale=next.PerformanceScale;if(next.Ready)taps.Observe(next.Total,next.Lifetime);Thread.Sleep(100);}
    if(p.IsConnected){Diag.Write(LogLevel.Info,"Connection","unload.requested","Runtime cleanup requested");writer.WriteLine("UNLOAD");ReadLineBounded(reader);Diag.Write(LogLevel.Info,"Connection","unload.acknowledged","Request acknowledged; cleanup completion logged by game component");}
   }
  }
  }catch(Exception e){if(!closed){if(StartupNotReady(e)){var log=Diag.Current;if(log!=null)log.Limited(LogLevel.Warn,"Connection","startup.not_ready","Bongo Cat is still initializing; attach will retry");Connection="waiting for game initialization";}else if(PipeDisconnected(e)){var log=Diag.Current;if(log!=null)log.Limited(LogLevel.Warn,"Connection","component.disconnected","Game component connection closed; recovery will retry");Connection="waiting for component";}else{Diag.Fault("Connection","disconnected",e);Connection=e.Message;}CosmeticCatalog="";Interlocked.Exchange(ref previewPending,int.MinValue);State=new GameState{Message=Connection};taps.ResetGuard();taps.PerformanceScale=0;}}finally{lock(gate){pipe=null;}}
 if(!closed)Thread.Sleep(1000);
 }}
 public void Dispose(){Running=false;closed=true;if(worker!=null&&!worker.Join(3500)){Diag.Write(LogLevel.Warn,"Connection","shutdown.timeout","Closing unresponsive control pipe");lock(gate){if(pipe!=null)pipe.Dispose();}worker.Join(500);}Diag.Write(LogLevel.Info,"Connection","polling.stop","Client stopped");}
}
