using System;using System.IO;using System.IO.Pipes;using System.Text;using System.Threading;using System.Diagnostics;using AutoCat.Diagnostics;
static class Tests {
 public static void Run(string path){var report=new StringBuilder();try{
  var f=TapEngine.Frame("10000000");if(f[0]!=0||f[1]!=16||Encoding.Unicode.GetString(f,2,f.Length-2)!="10000000")throw new Exception("Framing");report.AppendLine("PASS: tap protocol framing");
  if(TapEngine.Grant(25000000,7)!=7||TapEngine.Grant(1,0)!=0||TapEngine.Grant(100,-2)!=0)throw new Exception("Counter budget");
  using(var guard=new TapEngine("unused")){guard.Observe(1999999995,100);if(guard.Remaining!=5)throw new Exception("Cutoff");guard.Observe(100,100);if(guard.Remaining!=5)throw new Exception("Budget rollback");}report.AppendLine("PASS: counter cutoff, budget clamp, stale lower totals cannot enlarge budget");
  var state=GameState.Parse("OK|100|101|10|1|0|0|12|2|3|4|");if(!state.Ready||state.Lifetime!=101||!state.NormalReady||state.EmoteTimer!=12)throw new Exception("Bridge state");var tokens=GameState.Parse("OK|100|101|10|1|0|0|12|2|3|4||5|6|1|16.7|20|20|6|12");if(tokens.NormalTokens!=6||tokens.EmoteTokens!=12||state.NormalTokens!=-1||new Settings().InstaGift)throw new Exception("Token telemetry/defaults");report.AppendLine("PASS: token telemetry, legacy unknown balances and insta gift off by default");
  if(!BridgeClient.StartupNotReady(new Exception("Input hook not initialized"))||!BridgeClient.StartupNotReady(new Exception("Bongo Cat not initialized"))||BridgeClient.StartupNotReady(new Exception("Access denied")))throw new Exception("Startup readiness classification");if(!BridgeClient.PipeDisconnected(new IOException("Pipe is broken."))||BridgeClient.PipeDisconnected(new IOException("Bridge response timed out"))||BridgeClient.PipeDisconnected(new Exception("Pipe is broken.")))throw new Exception("Pipe disconnect classification");report.AppendLine("PASS: startup readiness and expected pipe disconnects are classified narrowly");
  if(!MainForm.Matches(5,2,5,2)||MainForm.Matches(5,2,5,0)||MainForm.Matches(0,0,0,0)||!MainForm.Matches(256,0,256,0))throw new Exception("Bindings");report.AppendLine("PASS: mouse / wheel / modifier bindings and unbound state");
  var settings=new Settings{Taps=100000000,MenuKey=5,MenuModifiers=2,PauseKey=257,Clicker=true,Gifts=true,Exchange=true,Emoting=true,InstaGift=true,EmoteRate=7};string tmp=Path.Combine(Path.GetTempPath(),"autocat-settings-"+Guid.NewGuid()+".xml");try{settings.Save(tmp);var copy=Settings.Read(tmp);if(copy.MenuKey!=5||copy.MenuModifiers!=2||copy.PauseKey!=257||!copy.Gifts||!copy.InstaGift||!copy.Emoting||copy.EmoteRate!=7||copy.Taps!=200||settings.Taps!=100000000)throw new Exception("Persistence");settings.ExtremeRates=true;settings.EmoteRate=1000;settings.Save(tmp);var extreme=Settings.Read(tmp);var restored=new RatePolicy();restored.Restore(extreme.ExtremeRates);if(!restored.Enabled||restored.Pending||extreme.Taps!=100000000||extreme.EmoteRate!=1000)throw new Exception("Confirmed rates persistence");settings.ExtremeRates=false;settings.Save(tmp);if(Settings.Read(tmp).ExtremeRates||Settings.Read(tmp).EmoteRate!=100)throw new Exception("Disabled rate persistence");settings.Taps=3;settings.Save(tmp);if(Settings.Read(tmp).Taps!=3)throw new Exception("Atomic overwrite");}finally{File.Delete(tmp);}report.AppendLine("PASS: settings round trip and atomic overwrite");
    var policy=new RatePolicy();if(new Settings().Taps!=10||new Settings().EmoteRate!=10||policy.Enabled||policy.Clamp(int.MaxValue,false)!=200||policy.Clamp(int.MaxValue,true)!=100)throw new Exception("Safe defaults");policy.Confirm();if(policy.Enabled)throw new Exception("Unrequested confirmation");policy.Request(true);if(policy.Enabled||!policy.Pending||policy.Clamp(1000,false)!=200||policy.Clamp(1000,true)!=100)throw new Exception("Pending bypass");policy.Request(false);policy.Confirm();if(policy.Enabled)throw new Exception("Cancelled confirmation");policy.Request(true);policy.Confirm();if(!policy.Enabled||policy.Pending||policy.Clamp(1000,false)!=1000||policy.Clamp(int.MaxValue,false)!=TapEngine.MaximumRate||policy.Clamp(1000,true)!=1000||policy.Clamp(int.MinValue,false)!=1)throw new Exception("Danger bounds");policy.Request(false);if(policy.Clamp(1000,false)!=200||policy.Clamp(1000,true)!=100||policy.Pending||policy.Enabled)throw new Exception("Disable clamp");report.AppendLine("PASS: danger confirmation, cancellation, independent normal caps and hard ceilings");
  string legacy=Path.Combine(Path.GetTempPath(),"autocat-legacy-"+Guid.NewGuid()+".xml");try{File.WriteAllText(legacy,"<Settings><Taps>100000000</Taps><EmoteRate>2147483647</EmoteRate></Settings>");var loaded=Settings.Read(legacy);if(loaded.Taps!=200||loaded.EmoteRate!=100)throw new Exception("Legacy unsafe rates");}finally{File.Delete(legacy);}report.AppendLine("PASS: legacy rates use independent normal clamps; saving does not alter live session rates");
  DiagnosticsHandoff();report.AppendLine("PASS: menu and runtime diagnostics handoff writes one shared session file");
  Transport();report.AppendLine("PASS: connected tap delivery, pause, resume, stale-counter stop and unload");File.WriteAllText(path,report.ToString());
 }catch(Exception e){File.WriteAllText(path,report+"FAIL: "+e);Environment.ExitCode=1;}}
 static int ReadTap(NamedPipeClientStream p){var head=Read(p,2);int count=head[0]*256+head[1];return int.Parse(Encoding.Unicode.GetString(Read(p,count)));}
 static byte[] Read(Stream p,int n){var b=new byte[n];int offset=0;while(offset<n){var a=p.BeginRead(b,offset,n-offset,null,null);using(a.AsyncWaitHandle){if(!a.AsyncWaitHandle.WaitOne(3000))throw new Exception("Read timeout");int got=p.EndRead(a);if(got==0)throw new Exception("EOF");offset+=got;}}return b;}
 static void DiagnosticsHandoff(){string priorSession=Diag.Session;LogLevel priorLevel=Diag.Level;string session=Guid.NewGuid().ToString("N"),folder=Path.Combine(Path.GetTempPath(),"autocat-diagnostics-"+Guid.NewGuid().ToString("N"));try{Diag.Session=session;Diag.Level=LogLevel.Info;string[] command=DiagnosticSession.Handshake().Split('|');if(command.Length!=4||command[0]!="LOG"||command[1]!=session||Encoding.UTF8.GetString(Convert.FromBase64String(command[3]))!=DiagnosticSession.Folder)throw new Exception("Diagnostic handoff command");using(var menu=new DiagnosticLog("menu"))using(var game=new DiagnosticLog("game")){menu.Configure(folder,session,LogLevel.Info);game.Configure(folder,session,LogLevel.Info);menu.Write(LogLevel.Info,"Integration","menu.record","menu marker");game.Write(LogLevel.Info,"Integration","game.record","game marker");menu.Dispose();game.Dispose();if(!menu.WaitForDrain(3000)||!game.WaitForDrain(3000))throw new Exception("Diagnostic drain");}string path=Path.Combine(folder,"diagnostic-"+session+".log");if(!File.Exists(path)||Directory.GetFiles(folder,"diagnostic-*.log").Length!=1)throw new Exception("Shared diagnostic session file");string text=File.ReadAllText(path);if(text.IndexOf("[menu] [Integration] menu.record",StringComparison.Ordinal)<0||text.IndexOf("[game] [Integration] game.record",StringComparison.Ordinal)<0)throw new Exception("Shared diagnostic records");}finally{Diag.Session=priorSession;Diag.Level=priorLevel;if(Directory.Exists(folder))Directory.Delete(folder,true);}}
 static void Transport(){string name="autocat-test-"+Guid.NewGuid().ToString("N");using(var engine=new TapEngine(name)){engine.Rate=100;engine.Enabled=true;engine.Observe(0,0);engine.Start();using(var p=new NamedPipeClientStream(".",name,PipeDirection.InOut,PipeOptions.Asynchronous)){p.Connect(3000);int total=0;for(int i=0;i<4;i++)total+=ReadTap(p);if(total<25||total>100)throw new Exception("Rate");engine.Enabled=false;ReadTap(p);if(ReadTap(p)!=0||ReadTap(p)!=0)throw new Exception("Pause");engine.Enabled=true;engine.Observe(100,100);if(ReadTap(p)==0&&ReadTap(p)==0)throw new Exception("Resume");for(int i=0;i<25;i++)ReadTap(p);if(ReadTap(p)!=0)throw new Exception("Stale counter must stop taps");engine.Dispose();}}}
}
